---
title: "Blue Rockfish Cross Correlation"
author: "Erin Johnston"
date: "6/23/2021"
output: 
  prettydoc::html_pretty:
    theme: cayman
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = F)

```

[back](https://erinmarjo.github.io/CCFRP/27_thesis_progress_report.html)

```{r libraries, warning=F, message=F}

library(tidyverse)
library(here)
library(knitr) ## for kable()
library(kableExtra) ## for save_kable()

```


```{r}

master <- read_csv(here("Data", "2021-06-28_full_master_2020.csv"))

blue_full <- master %>%
  filter(species == "BLU") 

missing_bl_blue <- data.frame(area = c("BL", "BL", "BL", "BL"),
                              site = c("REF", "MPA", "REF", "MPA"),
                              year = c(2007, 2007, 2015, 2015), 
                              cpue_site = c(NA, NA, NA, NA))

juv <- blue_full %>%
  filter(size <= 21) %>%
  select(-size) %>%
  group_by(drift, trip, area, site, month, day, year, gridcell) %>%
  summarise(cpue_sum = sum(cpue))%>%
  group_by(trip, area, site, month, day, year, gridcell) %>%
  summarise(cpue_date = mean(cpue_sum))%>%
  group_by( area, site, year, gridcell) %>%
  summarise(cpue_cell = mean(cpue_date))%>%
  group_by( area, site, year) %>%
  summarise(cpue_site = mean(cpue_cell)) %>%
  bind_rows(missing_bl_blue)


adult <- blue_full %>%
  filter(size >= 32) %>%
  select(-size)%>%
  group_by(drift, trip, area, site, month, day, year, gridcell) %>%
  summarise(cpue_sum = sum(cpue))%>%
  group_by(trip, area, site, month, year, gridcell) %>%
  summarise(cpue_date = mean(cpue_sum)) %>%
  group_by( area, site, year, gridcell) %>%
  summarise(cpue_cell = mean(cpue_date)) %>%
  group_by( area, site, year) %>%
  summarise(cpue_site = mean(cpue_cell))%>%
  bind_rows(missing_bl_blue)


## interesting thought to see where the fish in between adult and juvenile end up

teen <- blue_full %>%
  filter(size > 21 & size < 32) %>%
  select(-size)%>%
  group_by(drift, trip, area, site, month, day, year, gridcell) %>%
  summarise(cpue_sum = sum(cpue))%>%
  group_by(trip, area, site, month, year, gridcell) %>%
  summarise(cpue_date = mean(cpue_sum)) %>%
  group_by( area, site, year, gridcell) %>%
  summarise(cpue_cell = mean(cpue_date)) %>%
  group_by( area, site, year) %>%
  summarise(cpue_site = mean(cpue_cell))%>%
  bind_rows(missing_bl_blue)

```


```{r data with na}

MOCI <- read_csv(here("Data", "Central_California_MOCI_2020.csv"))

juv_moci <- left_join(juv, MOCI, by = "year") 
adult_moci <- left_join(adult, MOCI, by = "year")
teen_moci <- left_join(teen, MOCI, by = "year")

## just want to see something
# juv_moci <- juv_moci %>%
#   filter(year %in% c(2007:2019))

```


```{r write csvs, echo = F, eval = F}

#write_csv()

# write_csv(juv_moci, here("Data", "2021-07-04_juv_blue_moci_site_cpue.csv"))
# write_csv(adult_moci, here("Data", "2021-07-04_adult_blue_moci_site_cpue.csv"))

```

```{r, eval = F, echo = F}

## checking to make sure that adding NA's as a different dataframe was the same as manually adding NA's for Piedras Blancas in both 2015 and 2007 for the REF and MPA.
## It is. So there, I can do so for the other species as well.

juv2 <- blue_full %>%
  filter(size <= 21) %>%
  select(-size) %>%
  group_by(drift, trip, area, site, month, day, year, gridcell) %>%
  summarise(cpue_sum = sum(cpue))%>%
  group_by(trip, area, site, month, day, year, gridcell) %>%
  summarise(cpue_date = mean(cpue_sum))%>%
  group_by( area, site, year, gridcell) %>%
  summarise(cpue_cell = mean(cpue_date))%>%
  group_by( area, site, year) %>%
  summarise(cpue_site = mean(cpue_cell))

write_csv(juv2, here("Data", "2021-07-04_juv_blue_site_cpue.csv"))
juv_na <- read_csv(here("Data", "2021-07-04_juv_blue_site_cpue_NA.csv"))

juv_moci2 <- left_join(juv_na, MOCI, by = "year") 

anti_juv <- juv_moci %>%
  unite(col = "joined", c("area", "site", "year", "season"), sep = "_")

anti_juv2 <- juv_moci2 %>%
  unite(col = "joined", c("area", "site", "year", "season"), sep = "_")

different <- anti_join(anti_juv, anti_juv2, by = "joined")

```


### Cross Correlation Function

```{r custom function}
erin_ccf <- function(full_x, full_y, lag_x_rm, lag_y_rm) {
  mean_x <- mean(full_x, na.rm = T)
  mean_y <- mean(full_y, na.rm = T)
  corval <- (sum((lag_x_rm - mean_x)*
                   (lag_y_rm - mean_y)))/
    ((sqrt(sum((full_x - mean_x)^2, na.rm = T)))*
       (sqrt(sum((full_y - mean_y)^2, na.rm = T))))
  return(corval)
  
}
```


```{r loop set up}

juv_corr <- data.frame(area = character(), site = character(), season = character(), lag = character(), correlation = character())

adult_corr <- data.frame(area = character(), site = character(), season = character(), lag = character(), correlation = character())

teen_corr <- data.frame(area = character(), site = character(), season = character(), lag = character(), correlation = character())

area_list <- c("PB", "BL", "AN", "PL")
site_list <- c("MPA", "REF")
season_list <- c("JFM", "AMJ", "JAS", "OND")

```

## Juvenile Blue Rockfish

```{r juv loop}
for(j in area_list){
  for(k in site_list){
    for(l in season_list){
      juvenile <- juv_moci %>%
        filter(area == j, site == k, season == l)
      for(i in 0:8){
        lag_df <- juvenile %>%
          mutate(central_ca = dplyr::lag(central_ca, n = i)) %>% drop_na()
        cor <- erin_ccf(juvenile$central_ca, juvenile$cpue_site,
                        lag_df$central_ca, lag_df$cpue_site)
        for(m in 1:length(cor)){
          juv_corr <- bind_rows(juv_corr, c(area = j, site = k, season = l, 
                                            lag = -i, correlation = cor[m]))
        }
      }
    }
  }
} 


juv_vis <- juv_corr %>%
  mutate(correlation = as.numeric(correlation),
         lag = as.numeric(lag),
         Season = case_when(
    season == "JFM" ~ "Winter",
    season == "AMJ" ~ "Spring",
    season == "JAS" ~ "Summer",
    season == "OND" ~ "Fall"
  ), Area = case_when(
    area == "AN" ~ "A\u00f1o Nuevo",
    area == "PL" ~ "Point Lobos",
    area == "BL" ~ "Piedras Blancas",
    area == "PB" ~ "Point Buchon"
  ))
  
juv_vis$season <- factor(juv_vis$season, levels = c("JFM", "AMJ" ,"JAS", "OND"))
juv_vis$Season <- factor(juv_vis$Season, levels = c("Winter", "Spring" ,"Summer", "Fall"))  
juv_vis$Area <- factor(juv_vis$Area, levels = c("A\u00f1o Nuevo", "Point Lobos" ,"Piedras Blancas", "Point Buchon"))  


juv_plot_erin_ccf <- ggplot()+
  scale_color_manual(values = c("#999999", "#009999", "#666666", "#000000"))+
  scale_fill_manual(values = c("#999999", "#009999", "#666666", "#000000"))+
  geom_col(position = "dodge2", data = juv_vis, aes(x = lag, y = correlation, 
                                                    color = Season, fill = Season))+
  labs(title = "Juvenile Blue Rockfish Lag Correlation")+
  scale_y_continuous(limits = c(-0.6, 1.0), 
                     breaks = c(-0.6, -0.4, -0.2, 0.0, 0.2, 0.4, 0.6, 0.8, 1.0))+
  theme_bw()+
  theme(panel.grid = element_blank(),
        plot.title = element_text(hjust = 0.5))+
  facet_grid(site~Area)

```

### Cross Correlation Figure
#### Juvenile Blue Rockfish vs MOCI

```{r juv result and figure}

juv_vis %>%
  arrange(desc(abs(correlation))) %>%
  group_by(area, site) %>%
  slice(1)


juv_plot_erin_ccf

```

### Highest Correlation Figure

```{r top juv figure}

top_juv <- juv_vis %>% 
  arrange(desc(correlation)) %>% 
  group_by(area, site) %>% slice(1)


top_juv_meeting <- top_juv %>%
  mutate(Season = case_when(
    season == "JFM" ~ "Winter",
    season == "AMJ" ~ "Spring",
    season == "JAS" ~ "Summer",
    season == "OND" ~ "Fall"
  ), Lag = case_when(
    lag == "-2" ~ "2",
    lag == "-1" ~ "1"
  ), Area = case_when(
    area == "AN" ~ "A\u00f1o Nuevo",
    area == "PL" ~ "Point Lobos",
    area == "BL" ~ "Piedras Blancas",
    area == "PB" ~ "Point Buchon"
  ))

top_juv_meeting$area <- factor(top_juv_meeting$area, levels = c("AN", "PL", "BL", "PB"))
top_juv_meeting$Area <- factor(top_juv_meeting$Area, levels = c("A\u00f1o Nuevo", "Point Lobos", "Piedras Blancas", "Point Buchon"))
top_juv_meeting$Season <- factor(top_juv_meeting$Season, 
                                 levels = c("Winter", "Spring", "Summer", "Fall"))


top_juv_2020_dat <- top_juv_meeting %>%
  ggplot()+
  geom_point(size = 4, aes(x = Area, y = correlation, color = Season, 
                           fill = Season, shape = Lag))+
  scale_color_manual(values = c("#009999","#666666", "#000000"))+
  scale_fill_manual(values = c("#009999", "#666666", "#000000"))+
  scale_shape_manual(values = c(15, 19))+
  labs(title = "Juvenile Blue Rockfish Top Correlation CPUE-MOCI", 
       y = "Correlation\n", x = "\nArea (N to S)", caption = "")+
  scale_y_continuous(limits = c(0.0, 1.0), 
                     breaks = c(0.0, 0.2, 0.4, 0.6, 0.8, 1.0))+
  facet_wrap(.~site)+
  theme_bw()+
    theme(panel.grid = element_blank(),
          plot.title = element_text(hjust = 0.5),
          plot.caption = element_text(size = 8),
          axis.text.x = element_text(face = "bold",angle = 45, hjust =1))


top_juv_2020_dat


```

## Adult Blue Rockfish


```{r adult loop}
for(j in area_list){
  for(k in site_list){
    for(l in season_list){
      adult <- adult_moci %>%
        filter(area == j, site == k, season == l)
      for(i in 0:8){
        lag_df <- adult %>%
          mutate(central_ca = dplyr::lag(central_ca, n = i)) %>% drop_na()
        cor <- erin_ccf(adult$central_ca, adult$cpue_site,
                        lag_df$central_ca, lag_df$cpue_site)
        for(m in 1:length(cor)){
          adult_corr <- bind_rows(adult_corr, c(area = j, site = k, season = l, 
                                            lag = -i, correlation = cor[m]))
        }
      }
    }
  }
} 



adult_vis <- adult_corr %>%
  mutate(correlation = as.numeric(correlation),
         lag = as.numeric(lag),
         Season = case_when(
    season == "JFM" ~ "Winter",
    season == "AMJ" ~ "Spring",
    season == "JAS" ~ "Summer",
    season == "OND" ~ "Fall"
  ), Area = case_when(
    area == "AN" ~ "A\u00f1o Nuevo",
    area == "PL" ~ "Point Lobos",
    area == "BL" ~ "Piedras Blancas",
    area == "PB" ~ "Point Buchon"
  ))
  
adult_vis$season <- factor(adult_vis$season, levels = c("JFM", "AMJ" ,"JAS", "OND"))  
adult_vis$Season <- factor(juv_vis$Season, levels = c("Winter", "Spring" ,"Summer", "Fall"))  
adult_vis$Area <- factor(juv_vis$Area, levels = c("A\u00f1o Nuevo", "Point Lobos" ,"Piedras Blancas", "Point Buchon")) 

adult_plot_erin_ccf <- ggplot()+
  scale_color_manual(values = c("#999999", "#009999", "#666666", "#000000"))+
  scale_fill_manual(values = c("#999999", "#009999", "#666666", "#000000"))+
  geom_col(position = "dodge2", data = adult_vis, aes(x = lag, y = correlation,
                                                      color = Season, fill = Season))+
  labs(title = "Adult Blue Rockfish Lag Correlation")+
  scale_y_continuous(limits = c(-0.6, 1.0), 
                     breaks = c(-0.6, -0.4, -0.2, 0.0, 0.2, 0.4, 0.6, 0.8, 1.0))+
  theme_bw()+
  theme(panel.grid = element_blank(),
        plot.title = element_text(hjust = 0.5))+
  facet_grid(site~Area)

```

### Cross Correlation Figure
#### Adult Blue Rockfish vs MOCI

```{r adult result and figure}

adult_vis %>%
  arrange(desc(correlation)) %>%
  group_by(area, site) %>%
  slice(1)

adult_plot_erin_ccf

```

### Highest Correlation Figure

```{r top adult figure}

top_adult <- adult_vis %>% 
  arrange(desc(correlation)) %>% 
  group_by(area, site) %>% slice(1)


top_adult_meeting <- top_adult %>%
  mutate(Season = case_when(
    season == "JFM" ~ "Winter",
    season == "AMJ" ~ "Spring",
    season == "JAS" ~ "Summer",
    season == "OND" ~ "Fall"
  ), Lag = case_when(
    lag == "0" ~ "0",
    lag == "-1" ~ "1",
    lag == "-2" ~ "2",
    lag == "-3" ~ "3",
    lag == "-4" ~ "4"
  ), Area = case_when(
    area == "AN" ~ "A\u00f1o Nuevo",
    area == "PL" ~ "Point Lobos",
    area == "BL" ~ "Piedras Blancas",
    area == "PB" ~ "Point Buchon"
  )) 

top_adult_meeting$area <- factor(top_adult_meeting$area, levels = c("AN", "PL", "BL", "PB"))
top_adult_meeting$Area <- factor(top_adult_meeting$Area, levels = c("A\u00f1o Nuevo", "Point Lobos", "Piedras Blancas", "Point Buchon"))
top_adult_meeting$Season <- factor(top_adult_meeting$Season, 
                                 levels = c("Winter", "Spring", "Summer", "Fall"))



top_adult_2020_dat <-  top_adult_meeting %>%
  ggplot()+
  geom_point(size = 4, aes(x = Area, y = correlation, 
                           color = Season, fill = Season, shape = Lag))+
  scale_color_manual(values = c("#009999","#666666", "#000000"))+
  scale_fill_manual(values = c( "#009999","#666666", "#000000"))+
  scale_shape_manual(values = c(18, 15, 19, 17))+
  labs(title = "Adult Blue Rockfish Top Correlation CPUE-MOCI", y = "Correlation\n",
       x = "\nArea (N to S)", caption = "")+
  scale_y_continuous(limits = c(0.0, 1.0), 
                     breaks = c(0.0, 0.2, 0.4, 0.6, 0.8, 1.0))+  
  facet_wrap(.~site)+
  theme_bw()+
    theme(panel.grid=element_blank(),
          plot.title = element_text(hjust = 0.5),
          plot.caption = element_text(size = 8),
          axis.text.x = element_text(face = "bold",angle = 45, hjust =1))

top_adult_2020_dat

```


## Teen Blue Rockfish

```{r teen loop}
for(j in area_list){
  for(k in site_list){
    for(l in season_list){
      teenager <- teen_moci %>%
        filter(area == j, site == k, season == l)
      for(i in 0:8){
        lag_df <- teenager %>%
          mutate(central_ca = dplyr::lag(central_ca, n = i)) %>% drop_na()
        cor <- erin_ccf(teenager$central_ca, teenager$cpue_site,
                        lag_df$central_ca, lag_df$cpue_site)
        for(m in 1:length(cor)){
          teen_corr <- bind_rows(teen_corr, c(area = j, site = k, season = l, 
                                            lag = -i, correlation = cor[m]))
        }
      }
    }
  }
} 


teen_vis <- teen_corr %>%
  mutate(correlation = as.numeric(correlation),
         lag = as.numeric(lag),
         Season = case_when(
    season == "JFM" ~ "Winter",
    season == "AMJ" ~ "Spring",
    season == "JAS" ~ "Summer",
    season == "OND" ~ "Fall"
  ), Area = case_when(
    area == "AN" ~ "A\u00f1o Nuevo",
    area == "PL" ~ "Point Lobos",
    area == "BL" ~ "Piedras Blancas",
    area == "PB" ~ "Point Buchon"
  ))
  
teen_vis$season <- factor(teen_vis$season, levels = c("JFM", "AMJ" ,"JAS", "OND"))
teen_vis$Season <- factor(teen_vis$Season, levels = c("Winter", "Spring" ,"Summer", "Fall"))  
teen_vis$Area <- factor(teen_vis$Area, levels = c("A\u00f1o Nuevo", "Point Lobos" ,"Piedras Blancas", "Point Buchon"))  


teen_plot_erin_ccf <- ggplot()+
  scale_color_manual(values = c("#999999", "#009999", "#666666", "#000000"))+
  scale_fill_manual(values = c("#999999", "#009999", "#666666", "#000000"))+
  geom_col(position = "dodge2", data = teen_vis, aes(x = lag, y = correlation, 
                                                    color = Season, fill = Season))+
  labs(title = "'Teenage' Blue Rockfish Lag Correlation")+
  scale_y_continuous(limits = c(-0.6, 1.0), 
                     breaks = c(-0.6, -0.4, -0.2, 0.0, 0.2, 0.4, 0.6, 0.8, 1.0))+
  theme_bw()+
  theme(panel.grid = element_blank(),
        plot.title = element_text(hjust = 0.5))+
  facet_grid(site~Area)

```


### Highest Correlation Figure

```{r top teen figure}

top_teen <- teen_vis %>% 
  arrange(desc(correlation)) %>% 
  group_by(area, site) %>% slice(1)


top_teen_meeting <- top_teen %>%
  mutate(Season = case_when(
    season == "JFM" ~ "Winter",
    season == "AMJ" ~ "Spring",
    season == "JAS" ~ "Summer",
    season == "OND" ~ "Fall"
  ), Lag = case_when(
    lag == "-4" ~ "4",
    lag == "-3" ~"3",
    lag == "-2" ~ "2",
    lag == "-1" ~ "1"
  ), Area = case_when(
    area == "AN" ~ "A\u00f1o Nuevo",
    area == "PL" ~ "Point Lobos",
    area == "BL" ~ "Piedras Blancas",
    area == "PB" ~ "Point Buchon"
  ))

top_teen_meeting$area <- factor(top_teen_meeting$area, levels = c("AN", "PL", "BL", "PB"))
top_teen_meeting$Area <- factor(top_teen_meeting$Area, levels = c("A\u00f1o Nuevo", "Point Lobos", "Piedras Blancas", "Point Buchon"))
top_teen_meeting$Season <- factor(top_teen_meeting$Season, 
                                 levels = c("Winter", "Spring", "Summer", "Fall"))


top_teen_2020_dat <- top_teen_meeting %>%
  ggplot()+
  geom_point(size = 4, aes(x = Area, y = correlation, color = Season, 
                           fill = Season, shape = Lag))+
  scale_color_manual(values = c("#009999","#666666", "#000000"))+
  scale_fill_manual(values = c("#009999", "#666666", "#000000"))+
  scale_shape_manual(values = c(15, 19, 17, 12))+
  labs(title = "'Teenager' Blue Rockfish Top Correlation CPUE-MOCI", 
       y = "Correlation\n", x = "\nArea (N to S)", caption = "")+
  scale_y_continuous(limits = c(0.0, 1.0), 
                     breaks = c(0.0, 0.2, 0.4, 0.6, 0.8, 1.0))+
  facet_wrap(.~site)+
  theme_bw()+
    theme(panel.grid = element_blank(),
          plot.title = element_text(hjust = 0.5),
          plot.caption = element_text(size = 8),
          axis.text.x = element_text(face = "bold",angle = 45, hjust =1))


top_teen_2020_dat


```


```{r saving images, eval = F, echo = F}

# 
# ggsave(filename = "2021-07-04_adult_blue_top_corr.png", plot = top_adult_2020_dat,
#        path = "C:/Users/erinj/Documents/Thesis/Figures/Lag/2021", dpi = 1000, width = 6,
#         height = 4)

ggsave(filename = "2022-01-20_adult_blue_top_corr.png", plot = top_adult_2020_dat,
       path = "C:/Users/erinj/Documents/Thesis/Figures/Lag/2022", dpi = 1000, width = 6, height = 4)


# write_csv(top_juv, here("Data", "2021-07-04_top_juv_dataframe.csv"))
# write_csv(top_adult, here("Data", "2021-07-04_top_adult_dataframe.csv"))

```


[back](https://erinmarjo.github.io/CCFRP/27_thesis_progress_report.html)

```{r, eval = F, echo=F}

# Run this in console: rmarkdown::render(input = here("Code", "31_blue_cross_corr_2020.Rmd"), output_dir = here("docs"))

```