---
title: "MOCI Plot & Data"
author: "Erin Johnston"
date: "11/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = F,
                      message = F)
```

```{r libraries}

library(tidyverse)
library(here)
library(lubridate)

```

This is the plot we talked about in the meeting 2021-11-10, where the seasonal MOCI values are repeated for every month in that season.

```{r monthly moci plot}

moci_monthly_dates <- read_csv(here("Data", "moci_monthly_dates.csv"))

moci_monthly_dates <- moci_monthly_dates %>%
      mutate(pos_neg = case_when(
        central_ca > 0 ~ "positive",
        central_ca < 0 ~ "negative"),
        date = as.Date(date, "%m/%d/%Y"))

ggplot()+
  geom_col(data = moci_monthly_dates,
           aes(x = date, y = central_ca, color = pos_neg, fill = pos_neg))+
  geom_hline(yintercept = 0)+
  scale_fill_manual(values = c("#0066CC", "#CC0000"))+
  scale_color_manual(values = c("#00008B", "#8B0000"))+
  scale_x_date(date_breaks = "2 year", date_labels = "%Y",
               limits = as.Date(c('2008-01-01','2020-12-01')))+
  labs(y = "MOCI", x = "")+
  theme_bw()+
  theme(panel.grid = element_blank(),
        legend.position = "none")

```

This is the original plot with the spline.

```{r MOCI with spline}

moci <- read_csv(here("Data", "CaliforniaMOCI_JFM1991-AMJ2021.csv"))


moci_central2 <- moci %>%
  select(year, season, central_ca) %>%
  filter(year %in% c(1991:2020)) %>%
  mutate(pos_neg = case_when(
    central_ca > 0 ~ "positive",
    central_ca < 0 ~ "negative"
  ))

spline.moci<- as.data.frame(spline(moci_central2$year, moci_central2$central_ca))

moci_central3 <- moci_central2 %>%
  filter(year %in% c(2008:2021))

ggplot() +
  geom_col(data = moci_central3, position = position_dodge2(), 
           aes(x = year, y = central_ca, color = pos_neg, fill = pos_neg))+
  geom_line(data = spline.moci, aes(x = x, y = y), size = 1)+
  geom_hline(yintercept = 0)+
  scale_fill_manual(values = c( "#0066CC", "#CC0000"))+
  scale_color_manual(values = c( "#00008B", "#8B0000")) +
  scale_x_continuous(limits=c(2008,2021),breaks = seq(2008, 2020, 1))+
  scale_y_continuous(limits = c(-8, 11), breaks = seq(-8, 11, 2))+
  labs(y = "MOCI",  x = "", caption = "Data Source: http://www.faralloninstitute.org/moci")+
  theme_bw()+
  theme(panel.grid = element_blank(),
        legend.position = "none",
        plot.caption = element_text(size = 5))


```

